version: "3"

services:

  mysql:
    container_name: test-database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: euromillions
    ports:
      - "3306:3306"
    volumes:
      - "./docker-entrypoint-initdb.d/draw.sql:/docker-entrypoint-initdb.d/draw.sql"
    restart: always
    networks:
      - local

  redis:
    container_name: test_redis
    image: redis:alpine
    ports:
      - "7000:6379"
    networks:
      - local

  front:
    container_name: test_front
    build:
     context: .
    ports:
      - "9000:9000"
    networks:
      - local
    volumes:
      - ./code/:/var/www/

networks:
  local:
    driver: bridge

