version: "3"

services:

  php7-mysql:
    container_name: php7-database
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "./db:/var/lib/mysql"
    networks:
      - local
    restart: always

    # Redis perhaps?

networks:
  local:
    driver: bridge